/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyDayIndexRouteImport } from './routes/my-day/index'
import { Route as SafetyDashboardRouteImport } from './routes/safety/dashboard'
import { Route as OwnerDashboardRouteImport } from './routes/owner/dashboard'
import { Route as MaintenanceDashboardRouteImport } from './routes/maintenance/dashboard'
import { Route as DriverHomeRouteImport } from './routes/driver/home'
import { Route as DispatchDashboardRouteImport } from './routes/dispatch/dashboard'
import { Route as BillingDashboardRouteImport } from './routes/billing/dashboard'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AuthBootstrapRouteImport } from './routes/auth/bootstrap'
import { Route as DriverLoadsLoadIdRouteImport } from './routes/driver/loads.$loadId'
import { Route as DispatchLoadsLoadIdRouteImport } from './routes/dispatch/loads.$loadId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyDayIndexRoute = MyDayIndexRouteImport.update({
  id: '/my-day/',
  path: '/my-day/',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyDashboardRoute = SafetyDashboardRouteImport.update({
  id: '/safety/dashboard',
  path: '/safety/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerDashboardRoute = OwnerDashboardRouteImport.update({
  id: '/owner/dashboard',
  path: '/owner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceDashboardRoute = MaintenanceDashboardRouteImport.update({
  id: '/maintenance/dashboard',
  path: '/maintenance/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHomeRoute = DriverHomeRouteImport.update({
  id: '/driver/home',
  path: '/driver/home',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchDashboardRoute = DispatchDashboardRouteImport.update({
  id: '/dispatch/dashboard',
  path: '/dispatch/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingDashboardRoute = BillingDashboardRouteImport.update({
  id: '/billing/dashboard',
  path: '/billing/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthBootstrapRoute = AuthBootstrapRouteImport.update({
  id: '/auth/bootstrap',
  path: '/auth/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoadsLoadIdRoute = DriverLoadsLoadIdRouteImport.update({
  id: '/driver/loads/$loadId',
  path: '/driver/loads/$loadId',
  getParentRoute: () => rootRouteImport,
} as any)
const DispatchLoadsLoadIdRoute = DispatchLoadsLoadIdRouteImport.update({
  id: '/dispatch/loads/$loadId',
  path: '/dispatch/loads/$loadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/bootstrap': typeof AuthBootstrapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/billing/dashboard': typeof BillingDashboardRoute
  '/dispatch/dashboard': typeof DispatchDashboardRoute
  '/driver/home': typeof DriverHomeRoute
  '/maintenance/dashboard': typeof MaintenanceDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/safety/dashboard': typeof SafetyDashboardRoute
  '/my-day': typeof MyDayIndexRoute
  '/dispatch/loads/$loadId': typeof DispatchLoadsLoadIdRoute
  '/driver/loads/$loadId': typeof DriverLoadsLoadIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/bootstrap': typeof AuthBootstrapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/billing/dashboard': typeof BillingDashboardRoute
  '/dispatch/dashboard': typeof DispatchDashboardRoute
  '/driver/home': typeof DriverHomeRoute
  '/maintenance/dashboard': typeof MaintenanceDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/safety/dashboard': typeof SafetyDashboardRoute
  '/my-day': typeof MyDayIndexRoute
  '/dispatch/loads/$loadId': typeof DispatchLoadsLoadIdRoute
  '/driver/loads/$loadId': typeof DriverLoadsLoadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth/bootstrap': typeof AuthBootstrapRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/billing/dashboard': typeof BillingDashboardRoute
  '/dispatch/dashboard': typeof DispatchDashboardRoute
  '/driver/home': typeof DriverHomeRoute
  '/maintenance/dashboard': typeof MaintenanceDashboardRoute
  '/owner/dashboard': typeof OwnerDashboardRoute
  '/safety/dashboard': typeof SafetyDashboardRoute
  '/my-day/': typeof MyDayIndexRoute
  '/dispatch/loads/$loadId': typeof DispatchLoadsLoadIdRoute
  '/driver/loads/$loadId': typeof DriverLoadsLoadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/bootstrap'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/billing/dashboard'
    | '/dispatch/dashboard'
    | '/driver/home'
    | '/maintenance/dashboard'
    | '/owner/dashboard'
    | '/safety/dashboard'
    | '/my-day'
    | '/dispatch/loads/$loadId'
    | '/driver/loads/$loadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/bootstrap'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/billing/dashboard'
    | '/dispatch/dashboard'
    | '/driver/home'
    | '/maintenance/dashboard'
    | '/owner/dashboard'
    | '/safety/dashboard'
    | '/my-day'
    | '/dispatch/loads/$loadId'
    | '/driver/loads/$loadId'
  id:
    | '__root__'
    | '/'
    | '/auth/bootstrap'
    | '/auth/forgot-password'
    | '/auth/sign-in'
    | '/billing/dashboard'
    | '/dispatch/dashboard'
    | '/driver/home'
    | '/maintenance/dashboard'
    | '/owner/dashboard'
    | '/safety/dashboard'
    | '/my-day/'
    | '/dispatch/loads/$loadId'
    | '/driver/loads/$loadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthBootstrapRoute: typeof AuthBootstrapRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  BillingDashboardRoute: typeof BillingDashboardRoute
  DispatchDashboardRoute: typeof DispatchDashboardRoute
  DriverHomeRoute: typeof DriverHomeRoute
  MaintenanceDashboardRoute: typeof MaintenanceDashboardRoute
  OwnerDashboardRoute: typeof OwnerDashboardRoute
  SafetyDashboardRoute: typeof SafetyDashboardRoute
  MyDayIndexRoute: typeof MyDayIndexRoute
  DispatchLoadsLoadIdRoute: typeof DispatchLoadsLoadIdRoute
  DriverLoadsLoadIdRoute: typeof DriverLoadsLoadIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-day/': {
      id: '/my-day/'
      path: '/my-day'
      fullPath: '/my-day'
      preLoaderRoute: typeof MyDayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety/dashboard': {
      id: '/safety/dashboard'
      path: '/safety/dashboard'
      fullPath: '/safety/dashboard'
      preLoaderRoute: typeof SafetyDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/dashboard': {
      id: '/owner/dashboard'
      path: '/owner/dashboard'
      fullPath: '/owner/dashboard'
      preLoaderRoute: typeof OwnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance/dashboard': {
      id: '/maintenance/dashboard'
      path: '/maintenance/dashboard'
      fullPath: '/maintenance/dashboard'
      preLoaderRoute: typeof MaintenanceDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/home': {
      id: '/driver/home'
      path: '/driver/home'
      fullPath: '/driver/home'
      preLoaderRoute: typeof DriverHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/dashboard': {
      id: '/dispatch/dashboard'
      path: '/dispatch/dashboard'
      fullPath: '/dispatch/dashboard'
      preLoaderRoute: typeof DispatchDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing/dashboard': {
      id: '/billing/dashboard'
      path: '/billing/dashboard'
      fullPath: '/billing/dashboard'
      preLoaderRoute: typeof BillingDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/bootstrap': {
      id: '/auth/bootstrap'
      path: '/auth/bootstrap'
      fullPath: '/auth/bootstrap'
      preLoaderRoute: typeof AuthBootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/loads/$loadId': {
      id: '/driver/loads/$loadId'
      path: '/driver/loads/$loadId'
      fullPath: '/driver/loads/$loadId'
      preLoaderRoute: typeof DriverLoadsLoadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dispatch/loads/$loadId': {
      id: '/dispatch/loads/$loadId'
      path: '/dispatch/loads/$loadId'
      fullPath: '/dispatch/loads/$loadId'
      preLoaderRoute: typeof DispatchLoadsLoadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthBootstrapRoute: AuthBootstrapRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  BillingDashboardRoute: BillingDashboardRoute,
  DispatchDashboardRoute: DispatchDashboardRoute,
  DriverHomeRoute: DriverHomeRoute,
  MaintenanceDashboardRoute: MaintenanceDashboardRoute,
  OwnerDashboardRoute: OwnerDashboardRoute,
  SafetyDashboardRoute: SafetyDashboardRoute,
  MyDayIndexRoute: MyDayIndexRoute,
  DispatchLoadsLoadIdRoute: DispatchLoadsLoadIdRoute,
  DriverLoadsLoadIdRoute: DriverLoadsLoadIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
